name: Pull request

on:
    pull_request:
        branches: [ "main" ]

jobs:

    build:
        timeout-minutes: 10
        strategy:
            matrix:
                configuration: [ Release ]
                os: [ ubuntu-latest ]

        runs-on: ${{ matrix.os }}

        env:
            Solution_Name: Persistify.sln

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Install .NET Core
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.0.x

            -   name: Execute unit tests
                timeout-minutes: 5
                run: dotnet test

            -   name: Build
                run: dotnet build --configuration ${{ matrix.configuration }}
